### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by zombie343** [Perkka2/EPSM#1]
I've used KICAD and Gerber, but the other files just confuse me. Are these printed circuit boards? Why post on GitHub vs say, OSHpark? I feel like I'm missing something obvious that might be solved by a screenshot. 

P.S. thank you for doing this, as I'm modding all of my various NESes, flash carts and converters to support expansion audio

**Comment by Perkka2** [comment]
Which files are confusing you? I am having all my NES projects here on GitHub.
There are mainly 3 PCBs here. 2x EPSM's and 1 simple audio mod board to get ordinary expansion audio to the NES without modding the NES

**Comment by zombie343** [comment]
Yes! I'm interested in the solderless expansion audio! Could I trouble you for 1-2 pictures? Can I have the solderless expansion board made via OSHpark or PCBWay?

**Comment by Perkka2** [comment]
I have now uploaded some example images of the NES version of the EPSM and the SFEAM.

I have used jlcpcb for my boards but I can not see why you would have any issues with other producers

**Comment by zombie343** [comment]
Thank you! I'm new to ordering PCBs so I appreciate the pictures and the recommendation!

**Comment by zombie343** [comment]
Stupid question: does the console boot into the EPSM instead of the cartridge? Or does this replicate/replay the audio of the plugged-in cart?

**Comment by Perkka2** [comment]
Discussion finished on discord
